/* Generated by Pyrex 0.9.3 on Fri Dec 10 19:48:23 2004 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "convert.h"
#include "stdlib.h"
#include "string.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "A fast implementation to read in data rows.\n";

/* Declarations from cache */

staticforward PyTypeObject __pyx_type_5cache_Cache;

struct __pyx_obj_5cache_Cache {
  PyObject_HEAD
  char (*buffer);
  int blen;
  PyObject *list;
};

static PyTypeObject *__pyx_ptype_5cache_Cache = 0;

/* Implementation of cache */

static int __pyx_f_5cache_5Cache___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5cache_5Cache___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":24 */
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":25 */
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":26 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list);
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list = __pyx_1;
  __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cache.Cache.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_5cache_5Cache_realloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5cache_5Cache_realloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":29 */
  __pyx_1 = (((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen == 0);
  if (__pyx_1) {

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":30 */
    ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen = 1024;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":32 */
    ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen = (((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen * 2);

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":33 */
    free(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer);
  }
  __pyx_L2:;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":34 */
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer = ((char (*))malloc(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen));

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("cache.Cache.realloc");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_append;
static PyObject *__pyx_n_realloc;

static PyObject *__pyx_f_5cache_5Cache_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5cache_5Cache_add[] = "Adds a new row to the table.\n		";
static PyObject *__pyx_f_5cache_5Cache_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_ps = 0;
  unsigned short __pyx_v_ncol;
  int __pyx_v_fsiz;
  char (*__pyx_v_s);
  int __pyx_v_bitset;
  PyObject *__pyx_v_row;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  long __pyx_3;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"ps",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_ps)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_ps);
  __pyx_v_row = Py_None; Py_INCREF(__pyx_v_row);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":44 */
  __pyx_1 = PyString_AsString(__pyx_v_ps); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_v_s = __pyx_1;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":46 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_v_row);
  __pyx_v_row = __pyx_2;
  __pyx_2 = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":47 */
  __pyx_v_ncol = convertUShort(__pyx_v_s);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":49 */
  __pyx_v_s = (&(__pyx_v_s[2]));

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":51 */
  for (__pyx_3 = 0; __pyx_3 < __pyx_v_ncol; ++__pyx_3) {
    __pyx_2 = PyInt_FromLong(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":52 */
    __pyx_v_fsiz = convertInt(__pyx_v_s);

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":54 */
    __pyx_v_s = (&(__pyx_v_s[4]));

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":56 */
    __pyx_4 = (__pyx_v_fsiz <= 0);
    if (__pyx_4) {

      /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":57 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_row, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
      Py_INCREF(Py_None);
      PyTuple_SET_ITEM(__pyx_5, 0, Py_None);
      __pyx_6 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;

      /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":58 */
      goto __pyx_L2;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":60 */
    while (1) {
      __pyx_L5:;
      __pyx_4 = ((__pyx_v_fsiz + 1) > ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen);
      if (!__pyx_4) break;

      /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":61 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_realloc); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_6 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
    }
    __pyx_L6:;

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":63 */
    strncpy(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer,__pyx_v_s,__pyx_v_fsiz);

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":64 */
    (((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer[__pyx_v_fsiz]) = 0;

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":65 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_row, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    __pyx_5 = PyString_FromString(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;

    /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":66 */
    __pyx_v_s = (&(__pyx_v_s[__pyx_v_fsiz]));
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":68 */
  __pyx_2 = PyObject_GetAttr(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_INCREF(__pyx_v_row);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_row);
  __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("cache.Cache.add");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_row);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_ps);
  return __pyx_r;
}

static PyObject *__pyx_f_5cache_5Cache_finish(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5cache_5Cache_finish(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_l;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_l = Py_None; Py_INCREF(__pyx_v_l);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":71 */
  free(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer);

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":72 */
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->buffer = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":73 */
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->blen = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":74 */
  Py_INCREF(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list);
  Py_DECREF(__pyx_v_l);
  __pyx_v_l = ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":75 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list);
  ((struct __pyx_obj_5cache_Cache *)__pyx_v_self)->list = __pyx_1;
  __pyx_1 = 0;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":76 */
  Py_INCREF(__pyx_v_l);
  __pyx_r = __pyx_v_l;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cache.Cache.finish");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_append, "append"},
  {&__pyx_n_realloc, "realloc"},
  {0, 0}
};

static PyObject *__pyx_tp_new_5cache_Cache(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5cache_Cache *p = (struct __pyx_obj_5cache_Cache *)o;
  p->list = Py_None; Py_INCREF(p->list);
  if (__pyx_f_5cache_5Cache___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_5cache_Cache(PyObject *o) {
  struct __pyx_obj_5cache_Cache *p = (struct __pyx_obj_5cache_Cache *)o;
  Py_XDECREF(p->list);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5cache_Cache(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5cache_Cache *p = (struct __pyx_obj_5cache_Cache *)o;
  if (p->list) {
    e = (*v)(p->list, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5cache_Cache(PyObject *o) {
  struct __pyx_obj_5cache_Cache *p = (struct __pyx_obj_5cache_Cache *)o;
  Py_XDECREF(p->list);
  p->list = Py_None; Py_INCREF(p->list);
  return 0;
}

static struct PyMethodDef __pyx_methods_5cache_Cache[] = {
  {"realloc", (PyCFunction)__pyx_f_5cache_5Cache_realloc, METH_VARARGS|METH_KEYWORDS, 0},
  {"add", (PyCFunction)__pyx_f_5cache_5Cache_add, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5cache_5Cache_add},
  {"finish", (PyCFunction)__pyx_f_5cache_5Cache_finish, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Cache = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Cache = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Cache = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Cache = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_5cache_Cache = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "cache.Cache", /*tp_name*/
  sizeof(struct __pyx_obj_5cache_Cache), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5cache_Cache, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Cache, /*tp_as_number*/
  &__pyx_tp_as_sequence_Cache, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Cache, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Cache, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "A Cache class for data rows.\n	", /*tp_doc*/
  __pyx_tp_traverse_5cache_Cache, /*tp_traverse*/
  __pyx_tp_clear_5cache_Cache, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5cache_Cache, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5cache_Cache, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initcache(void); /*proto*/
DL_EXPORT(void) initcache(void) {
  __pyx_m = Py_InitModule4("cache", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_type_5cache_Cache.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5cache_Cache) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Cache", (PyObject *)&__pyx_type_5cache_Cache) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_ptype_5cache_Cache = &__pyx_type_5cache_Cache;

  /* "/usr/home/jamwt/devel/pgasync/pgasync/cache.pyx":70 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("cache");
}

static char *__pyx_filenames[] = {
  "cache.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
